# Default values for wikijs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image: nginx:1.9.2

database:
  host: postgres
  port: "5432"
  user: postgres
  password: password
  name: wikijs

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hostname: 127.0.0.1.nip.io