# Default values for wikijs.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: requarks/wiki
  tag: latest

database:
  host: postgres
  port: "5432"
  user: postgres
  name: wikijs

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  hostname: 127.0.0.1.nip.io

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

postgresql:
  enabled: true
  postgresqlDatabase: wikijs
  persistence:
    enabled: true
    accessModes:
    - ReadWriteOnce
    size: 8Gi