
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transmission-deployment
spec:
  selector:
    matchLabels:
      app: transmission
  replicas: 1
  template:
    metadata:
      labels:
        app: transmission
    spec:
      containers:
      - name: transmission
        image: ghcr.io/linuxserver/transmission:3.00-r2-ls94
        ports:
        - containerPort: 9091
        readinessProbe:
          tcpSocket:
            port: 9091
        livenessProbe:
          tcpSocket:
            port: 9091
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: TZ
          value: "Europe/London"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: USER
          value: "seb"
        - name: PASS
          value: "azerty"