apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wikijs.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "wikijs.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wikijs.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "wikijs.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - secretRef:
              name: {{ include "wikijs.fullname" . }}
          env:
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{- template "wikijs.postgresql.fullname" . -}}
                key: postgresql-password
              ports:
                - name: http
                  containerPort: 3000
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /healthz
                  port: http
              readinessProbe:
                httpGet:
                  path: /healthz
                  port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}