{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{include "wikijs.fullname" .}}
spec:
  rules:
  - host: {{.Values.ingress.hostname}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{include "wikijs.fullname" .}}
          servicePort: {{.Values.service.port}}
{{- end }}