apiVersion: v1
data:
  DB_HOST: {{ .Values.database.host | b64enc }}
  DB_PORT: {{ .Values.database.port | b64enc }}
  DB_USER: {{ .Values.database.user | b64enc }}
  DB_NAME: {{ .Values.database.name | b64enc }}
kind: Secret
metadata:
  name: {{include "wikijs.fullname" .}}
type: Opaque