apiVersion: v1
kind: Service
metadata:
  name: {{include "wikijs.fullname" .}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector: {{- include "wikijs.selectorLabels" . | nindent 4}}
